# https://hub.docker.com/r/rocm/vllm/tags
FROM docker.io/rocm/vllm:rocm7.0.0_vllm_0.11.1_20251103

# Install essential utilities
RUN apt-get update && apt-get install -y curl net-tools iputils-ping nano tree

# Optional: Install VS Code Server
RUN curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' -o vscode_cli.tar.gz && \
    tar -xf vscode_cli.tar.gz && \
    mv code /usr/local/bin/code && \
    rm vscode_cli.tar.gz

# Install rclone and prepare config directory
# https://rclone.org/downloads/
RUN curl -Lk 'https://downloads.rclone.org/v1.71.2/rclone-v1.71.2-linux-amd64.deb' -o rclone-v1.71.2-linux-amd64.deb && \
    dpkg -i rclone-v1.71.2-linux-amd64.deb && \
    rm rclone-v1.71.2-linux-amd64.deb && \
    mkdir -p /root/.config/rclone

RUN pip install --upgrade pip
RUN pip install python-dotenv 
    
WORKDIR /app

COPY test_model_loading.py helper.py /app/

CMD ["python3", "test_model_loading.py"]
# Image: docker.io/richardxgf/amd:model_loading_1.0
# https://hub.docker.com/repository/docker/richardxgf/amd/tags

